name: Get Wikidata info

on:
  schedule:
    - cron:  '44 1 * * *'
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install dependencies
      run: |-
        sudo apt-get install jq moreutils
        npm install -g wikibase-cli
    - name: Run SPARQL queries
      run: for j in wikidata/queries/*.js; do wd sparql $j -f csv > /tmp/QS && sed -e 's#http://www.wikidata.org/entity/##g' -e 's/T00:00:00Z//g' /tmp/QS | ifne tee "wikidata/results/$(basename $j ".js").csv" ; done
    - name: Commit and push if results have changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add wikidata
        timestamp=$(date -u)
        git commit -m "refresh wikidata query results: ${timestamp}" || exit 0
        git push
